server:
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver  #引入sql性能分析插件p6spy后 需要更换驱动
    url: jdbc:mysql:///demo?useSSL=false&useUnicode=true&amp&characterEncoding=UTF-8   #引入sql性能分析插件p6spy后 需要更换url
    #    url: jdbc:p6spy:mysql://localhost:3306/world
    #    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: adminadmin
  application:
    name: demo-infrastructure

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full

  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以不加@TableLogic在实体类字段上)
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:com/flamelephant/mapper/*.xml
  type-aliases-package: com.flamelephant.model
